SUB 0
DEC
STORE 1 # p1 = -1
INC
INC
STORE 2 # p2 = 1
SHIFT 2
INC
SHIFT 2
SHIFT 2
STORE 3 #p3 = 12 => A
INC
STORE 4 # p4 = 13 => B # chcemy 13 * 12 więc trzeba wziąć najmniej ważny bit z 12
STORE 5 # WYNIK MNOŻENIA, NA RAZIE 13
LOAD 3 # ZAŁADUJ 12
SHIFT 1 # PRZESUŃ W PRAWO
SHIFT 2 # PRZESUŃ W LEWO
SUB 3 # OD 12 ODEJMIJ AKTUALNĄ WARTOŚĆ  JESLI 0 TO OSTATNI BIT TO ZERO , -1 TO BYŁO 1
JZERO 26
LOAD 5  #ZAŁADUJ WYNIK
ADD 4   # DODAJ B
STORE 5  # #ZAPISZ WYNIK
LOAD 4   #WEŹ B
PUT
SHIFT 2  # PRZESUŃ W LEWO
STORE 4  #ZAPISZ
LOAD 3  # WEŹ A
SHIFT 1 # PRZESUŃ W PRAWO
STORE 3 # ZAPISZ A
JZERO 31
JPOS 14
LOAD 5
PUT
HALT