SUB 0
STORE 5 #NASZ WYNIK = 0
DEC
STORE 1 # p1 = -1 przesuwanie w prawo
INC
INC
STORE 2 # p2 = 1 przesuwanie w lewo
SHIFT 2
INC
SHIFT 2
SHIFT 2
STORE 3 # p3 = 12 => A
INC
STORE 4 # p4 = 13 => B # chcemy 13 * 12 więc trzeba wziąć najmniej ważny bit z 12 A
LOAD 3  # ŁADUJEMY A
SHIFT 1 #PRZESUWAMY W PRAWO
SHIFT 2 #PRZESUWAMY W LEWO
SUB 3  # MAMY RÓŻNICE A I A'
JZERO 22 # MAMY 0 NA OSTATNIM BICIE (IF) +(WHILE)
LOAD 5 # WEŻ WYNIK
ADD 4 # DODAJ B
STORE 5 # ZAPISZ NOWY WYNIK (END IF)
LOAD 4 # WEZ B  # SKOCZEK Z W PRZYPADKU PRZESUNIĘCIA
SHIFT 2 # PRZESUN B W LEWO
STORE 4 # ZAPISZ B
LOAD 3 #WEZ A
SHIFT 1 #PRZESUWAMY W PRAWO
STORE 3 # ZAPISZ NOWE A
JZERO 30 # JESLI WARTOŚ A = 0 KONCZ
JUMP 14 # {END WHILE}
LOAD 5 # WYNIK
PUT # POKAŻ
HALT
